# Generated by Django 4.1 on 2024-06-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PARTNER_NGO'), (2, 'VOLUNTEER'), (3, 'MAIN_OFFICE')], default=1),
        ),
    ]
