# Generated by Django 4.1 on 2024-06-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_volunteer_ngo_volunteer_remove_student_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
