# Generated by Django 4.1 on 2024-06-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentforma',
            name='inst_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentforma',
            name='inst_interview_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentforma',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentforma',
            name='vol_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentforma',
            name='vol_interview_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
